### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by srkgupta** [cermak-petr/act-crawl-manager#1]
I get the following issue at times while running an Act. 

2018-07-08T05:21:48.040Z (node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
2018-07-08T05:21:48.042Z     at isCrawlerRunning (/usr/src/app/main.js:17:17)
2018-07-08T05:21:48.043Z     at <anonymous>
2018-07-08T05:21:48.045Z     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-07-08T05:21:48.046Z (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-07-08T05:21:48.048Z (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by srkgupta** [comment]
I fixed this issue by changing the following lines in the isCrawlerRunning function: 
    if(exec && exec.status === 'RUNNING'){
        return true;
    }else{
        return false;
    }

Also changed the following lines in the waitForCrawlerFinish function:
if(exec && exec.status != 'RUNNING'){
                clearInterval(interval);
                resolve(exec);
}
